/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs522bykowski_fittslaw;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.out;
import java.util.Arrays;
import java.util.Collections;

/**
 *
 * @author Karen
 */
public class FittsLaw extends javax.swing.JFrame {
    private long startTime;
    private long endTime;
    private long times[] = new long[6];
    private int count = 0;
    private Integer nums[] = new Integer[]{0, 1, 2, 3, 4, 5};

    /**
     * Creates new form FittsLaw
     */
    public FittsLaw() {
        Collections.shuffle(Arrays.asList(nums));  //make targets show randomly
        System.out.println(java.util.Arrays.toString(nums));   //////TESTING REMOVE
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        target1a = new javax.swing.JButton();
        target1c = new javax.swing.JButton();
        target1b = new javax.swing.JButton();
        target2a = new javax.swing.JButton();
        target2c = new javax.swing.JButton();
        target2b = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setBackground(new java.awt.Color(153, 255, 153));
        startButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        startButton.setText("Start");
        startButton.setActionCommand("startButton");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        target1a.setBackground(new java.awt.Color(0, 153, 153));
        target1a.setForeground(new java.awt.Color(0, 153, 153));
        target1a.setActionCommand("target1a");
        target1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                target1aActionPerformed(evt);
            }
        });

        target1c.setBackground(new java.awt.Color(0, 153, 153));
        target1c.setForeground(new java.awt.Color(0, 153, 153));
        target1c.setActionCommand("target1c");
        target1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                target1cActionPerformed(evt);
            }
        });

        target1b.setBackground(new java.awt.Color(0, 153, 153));
        target1b.setForeground(new java.awt.Color(0, 153, 153));
        target1b.setActionCommand("target1b");
        target1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                target1bActionPerformed(evt);
            }
        });

        target2a.setBackground(new java.awt.Color(0, 153, 153));
        target2a.setActionCommand("target2a");
        target2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                target2aActionPerformed(evt);
            }
        });

        target2c.setBackground(new java.awt.Color(0, 153, 153));
        target2c.setActionCommand("target2c");
        target2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                target2cActionPerformed(evt);
            }
        });

        target2b.setBackground(new java.awt.Color(0, 153, 153));
        target2b.setActionCommand("target2b");
        target2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                target2bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane()); 
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(target1c))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(startButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(521, 521, 521)
                                .addComponent(target1a)
                                .addGap(1, 1, 1)
                                .addComponent(target2a, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(978, 978, 978)
                .addComponent(target1b)
                .addGap(2, 2, 2)
                .addComponent(target2b, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(target2c, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(target1a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(target2a, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(target1b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(target2b, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(startButton)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(target2c, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(target1c, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        hideButtons();

    }// </editor-fold>//GEN-END:initComponents

    private void hideButtons() {
        target1a.setVisible(false);
        target1b.setVisible(false);
        target1c.setVisible(false);
        target2a.setVisible(false);
        target2b.setVisible(false);
        target2c.setVisible(false);
    }    
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        startTime = System.currentTimeMillis();
        
        switch(nums[count]) {
            case 0: 
                target1a.setVisible(true); //top small
                break;
            case 1:
                target2a.setVisible(true); //top big
                break;
            case 2:
                target1b.setVisible(true); //middle small
                break;
            case 3:
                target2b.setVisible(true); //middle big
                break;
            case 4:
                target1c.setVisible(true);  //bottom small
                break;
            case 5:
                target2c.setVisible(true);  //bottom big
                break;
            default:
                System.exit(0);
                break;
        }
    }//GEN-LAST:event_startButtonActionPerformed
    
    private void target1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_target1aActionPerformed
        targetPressed();
    }//GEN-LAST:event_target1aActionPerformed

    private void target2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_target2aActionPerformed
        targetPressed();
    }//GEN-LAST:event_target2aActionPerformed

    private void target1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_target1bActionPerformed
        targetPressed();
    }//GEN-LAST:event_target1bActionPerformed

    private void target2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_target2bActionPerformed
        targetPressed();
    }//GEN-LAST:event_target2bActionPerformed

    private void target2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_target2cActionPerformed
        targetPressed();
    }//GEN-LAST:event_target2cActionPerformed

    private void target1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_target1cActionPerformed
        targetPressed();
    }//GEN-LAST:event_target1cActionPerformed

    private void targetPressed() {
        endTime = System.currentTimeMillis();
        times[nums[count]] = endTime - startTime;
        hideButtons();
        System.out.println("time " + times[nums[count]]); //////TESTING REMOVE
        count++;
        
        if(count > 5) {
            //print to file
            try{
                BufferedWriter out = new BufferedWriter(new FileWriter("FittsLawOutput.txt", true));
                    out.write("New Entry " + System.currentTimeMillis() + "\n\t");
                    for(int i = 0; i < 6; i++) {
                        out.write(times[i] + "\n\t");
                    }
                    out.write("\n\n\t\t");
                    out.close();
            } catch(IOException e) {
                System.out.println("Exception occured");
            }
            
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        final FittsLaw fl = new FittsLaw();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FittsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FittsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FittsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FittsLaw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fl.setVisible(true);
                //new FittsLaw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton startButton;
    private javax.swing.JButton target1a;
    private javax.swing.JButton target1b;
    private javax.swing.JButton target1c;
    private javax.swing.JButton target2a;
    private javax.swing.JButton target2b;
    private javax.swing.JButton target2c;
    // End of variables declaration//GEN-END:variables
}
